name: Publish Container

on:
  push:
    branches:
      - ops/workflow

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push to GitHub Container Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ghcr.io/eos/strapi
          registry: ghcr.io
          githubOrg: EOS-uiux-Solutions
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT }}